## POS digunakan untuk mengidentifikasi sebuah kata merupakan jenis kata apa

In [1]:
import pandas as pd
import spacy

In [2]:
spacy.cli.download('en_core_web_sm')
nlp = spacy.load('en_core_web_sm')

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 488.9 kB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [3]:
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [4]:
spacy_doc = nlp(emma_ja)
spacy_doc

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [5]:
# memasukkan data ke dalam dataframe
pos_df = pd.DataFrame([{'token' : t.text, 'pos_tag' : t.pos_} for t in spacy_doc])
    
pos_df

         token pos_tag
0         emma   PROPN
1    woodhouse   PROPN
2     handsome     ADJ
3       clever     ADJ
4          and   CCONJ
..         ...     ...
209   directed    VERB
210    chiefly     ADV
211         by     ADP
212        her    PRON
213        own     ADJ

[214 rows x 2 columns]

In [15]:
pos_df_counts = pos_df.groupby(['token', 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)
pos_df_counts

         token pos_tag  counts
88          of     ADP      14
49         had     AUX       9
54         her    PRON       9
111        the     DET       8
6          and   CCONJ       8
..         ...     ...     ...
43      father    NOUN       1
42      family    NOUN       1
41      fallen    VERB       1
40   existence    NOUN       1
131   youngest     ADJ       1

[132 rows x 3 columns]

In [18]:
# menghitung jumlah data berdasarkan masing - masing pos_tag
pos_df_poscounts = pos_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)
pos_df_poscounts

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
NUM       3
SCONJ     3
PART      1
Name: token, dtype: int64

In [20]:
# menampilkan data berdasarkan pos_tag tertentu
nouns = pos_df_counts[pos_df_counts.pos_tag == "NOUN"]
nouns

           token pos_tag  counts
48     governess    NOUN       3
46        friend    NOUN       3
130        years    NOUN       2
35          emma    NOUN       2
28     daughters    NOUN       2
103      sisters    NOUN       2
82        mother    NOUN       2
89        office    NOUN       1
78      mistress    NOUN       1
75      mildness    NOUN       1
94        period    NOUN       1
95         place    NOUN       1
96   remembrance    NOUN       1
129        world    NOUN       1
126        woman    NOUN       1
121          vex    NOUN       1
109       temper    NOUN       1
108      taylors    NOUN       1
100       shadow    NOUN       1
97     restraint    NOUN       1
74      marriage    NOUN       1
66      judgment    NOUN       1
32      distress    NOUN       1
31   disposition    NOUN       1
27   consequence    NOUN       1
22      caresses    NOUN       1
18     blessings    NOUN       1
11     authority    NOUN       1
1      affection    NOUN       1
64      intimacy    NOUN       1
59         house    NOUN       1
58          home    NOUN       1
43        father    NOUN       1
42        family    NOUN       1
40     existence    NOUN       1